name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Note:** Feature requests require maintainer approval before implementation.
        Please wait for the `approved` label before starting work.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: dropdown
    id: skill
    attributes:
      label: Affected Skill
      description: Which skill is this related to?
      options:
        - otto
        - spec
        - task
        - next
        - test
        - review
        - summary
        - doc
        - clean
        - New skill
        - Multiple/Other
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this change break existing functionality?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the Code of Conduct
          required: true
